//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Psicho_Support.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthPsicho_DBEntities : DbContext
    {
        public HealthPsicho_DBEntities()
            : base("name=HealthPsicho_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievements> Achievements { get; set; }
        public virtual DbSet<AppUsageStats> AppUsageStats { get; set; }
        public virtual DbSet<Emotions> Emotions { get; set; }
        public virtual DbSet<Notes> Notes { get; set; }
        public virtual DbSet<PsychoTypes> PsychoTypes { get; set; }
        public virtual DbSet<SleepSessions> SleepSessions { get; set; }
        public virtual DbSet<TestResults> TestResults { get; set; }
        public virtual DbSet<Tests> Tests { get; set; }
        public virtual DbSet<UserAchievements> UserAchievements { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
