//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Psicho_Support.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SleepSessions
    {
        public int SleepID { get; set; }
        public int UserID { get; set; }
        public Nullable<double> HoursSlept { get; set; }
        public Nullable<int> SleepQuality { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
