//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Psicho_Support.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAchievements
    {
        public int UserAchievementID { get; set; }
        public int UserID { get; set; }
        public int AchievementID { get; set; }
        public Nullable<System.DateTime> DateEarned { get; set; }
    
        public virtual Achievements Achievements { get; set; }
        public virtual Users Users { get; set; }
    }
}
